### ISSUE TITLE
1.18.2 Height

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/IslandFly#90] opened 2022-06-20 11:43 UTC
### Expected behavior

Player can be fly in island limits.

### Observed/Actual behavior

Player's fly turning off when reach the 0 or 256 height. But in 1.18, this heights are -63 to 319.

### Steps/models to reproduce

Just need increase check heights for 1.18 version.

### BentoBox version

![image](https://user-images.githubusercontent.com/47111280/174593994-b8c1939f-6fd4-4a60-8568-639dacf626ea.png)

**Comment by BONNe** [comment] 2022-06-20 12:12
Duplicate of #87

**Closed by BONNe** 2022-06-20 12:12 UTC
